"""empty message

Revision ID: 3820bf28bfee
Revises: 3fe50412fc60
Create Date: 2015-05-24 21:50:25.056764

"""

# revision identifiers, used by Alembic.
revision = '3820bf28bfee'
down_revision = '3fe50412fc60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('course', sa.Float(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('archived_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gps_points')
    ### end Alembic commands ###
