"""empty message

Revision ID: 3eaa2f19084e
Revises: None
Create Date: 2015-05-19 13:43:31.698296

"""

# revision identifiers, used by Alembic.
revision = '3eaa2f19084e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
