"""empty message

Revision ID: 3fe50412fc60
Revises: 3eaa2f19084e
Create Date: 2015-05-19 13:49:24.281241

"""

# revision identifiers, used by Alembic.
revision = '3fe50412fc60'
down_revision = '3eaa2f19084e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number_priorities',
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('priority')
    )
    op.create_table('emergency_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('archived_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['priority'], ['number_priorities.priority'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_numbers')
    op.drop_table('number_priorities')
    ### end Alembic commands ###
