"""empty message

Revision ID: 4e04597ebfb5
Revises: 3fe50412fc60
Create Date: 2015-05-20 21:07:59.075724

"""

# revision identifiers, used by Alembic.
revision = '4e04597ebfb5'
down_revision = '3fe50412fc60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('course', sa.Float(), nullable=True),
    sa.Column('mode', sa.Enum('A', 'M', 'D', 'S', 'E', 'N', name='mode_indicator'), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('archived_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gps_points')
    ### end Alembic commands ###
