"""empty message

Revision ID: 5ac12761d383
Revises: None
Create Date: 2015-05-19 11:47:33.509635

"""

# revision identifiers, used by Alembic.
revision = '5ac12761d383'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
